report_task:
  description: >
    Based on the input topic: {topic}, generate a deatiled report including all the latest facts and future trends in a strucutred way. The report should be around 2000 words.
  expected_output: >
    2000 words long report on the topic: {topic}
  agent: report_generator

blog_writing_task:
  description: >
    Based on the report on {topic}, create a well written and strucutred blog that even a 5 year old can understand. the blog should be around 500 words.
  expected_output: >
    500 words long blog post on topic: {topic}. the blog should be well strucutred with a creative and fun heading.
  agent: blog_writer
